default: &default
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # SQLite3 specific settings
  pragmas:
    journal_mode: 'wal'
    synchronous: 'normal'
    temp_store: 'memory'
    mmap_size: '30000000000'
    busy_timeout: 5000

development:
  primary:
    <<: *default
    database: storage/development.sqlite3
  queue:
    <<: *default
    database: storage/development_queue.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  primary:
    <<: *default
    database: /data/production.sqlite3
  queue:
    <<: *default
    database: /data/production_queue.sqlite3
